import { StyleSheet, Dimensions } from "react-native";
import theme from "../config";

const { width } = Dimensions.get("window");
const NUM_COLUMNS = 3;
const TILE_WIDTH = width / NUM_COLUMNS;
const TILE_HEIGHT = TILE_WIDTH;
const TILE_SPACING = 1;

// Palette de couleurs inspirée du monde automobile et du racing
const THEME_COLORS = {
  primary: "#E10600", // Rouge Racing
  secondary: "#1E1E1E", // Noir Racing
  tertiary: "#2D9CDB", // Bleu pour accent
  quaternary: "#F0C419", // Jaune pour accent
  background: "#FFFFFF",
  card: "#F2F2F2",
  cardLight: "#F8F8F8",
  textPrimary: "#1E1E1E",
  textSecondary: "#6E6E6E",
  border: "#E0E0E0",
  success: "#27AE60", // Vert pour badges positifs
};

const styles = StyleSheet.create({  container: {
    flex: 1,
    backgroundColor: THEME_COLORS.background,
  },
  content: {
    flex: 1,
  },
  topBar: {
    height: 60,
    backgroundColor: THEME_COLORS.background,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: THEME_COLORS.border,
  },
  topBarContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topBarTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: THEME_COLORS.secondary,
  },  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: THEME_COLORS.background,
    borderBottomWidth: 0,
    zIndex: 10,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  menuButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "transparent",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  friendsButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "transparent",
    position: "relative",
    marginRight: 10,
  },
  friendsBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#E10600",
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  friendsBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "bold",
  },
  username: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 8,
  },
  title:{
     fontSize: 18,
    fontWeight: "bold",
    color: "#1A1A1A",
    flex: 1,
    textAlign: "center",
  },
  profileContainer: {
    flex: 0,
    backgroundColor: THEME_COLORS.background,
    borderBottomWidth: 6,
    borderBottomColor: THEME_COLORS.card,
  },
  profileSection: {
    paddingHorizontal: 15,
    paddingVertical: 15,
    backgroundColor: THEME_COLORS.background,
  },
  profileInfo: {
    flex: 1,
  },
  profileAvatar: {
    width: 90,
    height: 90,
    borderRadius: 10, // Carré avec coins arrondis au lieu de cercle
    marginRight: 15,
    borderWidth: 0,
    shadowColor: THEME_COLORS.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  profileDetails: {
    flex: 1,
    justifyContent: "flex-start",
    backgroundColor: THEME_COLORS.background,
  },

  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  statItem: {
    alignItems: "center",
  },
  statNumber: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1E1E1E",
  },
  statLabel: {
    fontSize: 14,
    color: "#666666",
  },
  bioSection: {
    marginBottom: 10,
    padding: 15,
    borderRadius: 10,
  },
  displayName: {
    fontSize: 18,
    fontWeight: "bold",
    color: THEME_COLORS.secondary,
    marginLeft: 10,
    marginBottom: 5,
  },
  bioText: {
    fontSize: 16,
    color: THEME_COLORS.secondary,
    marginBottom: 4,
    lineHeight: 20,
  },
  websiteLink: {
    marginTop: 8,
    backgroundColor: THEME_COLORS.card,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 4,
    alignSelf: "flex-start",
  },
  websiteText: {
    fontSize: 14,
    color: THEME_COLORS.tertiary,
    fontWeight: "500",
  },
  actionButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    marginBottom: 15,
    gap: 10,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  followButton: {
    backgroundColor: THEME_COLORS.primary,
  },
  followButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  messageButton: {
    backgroundColor: "#E0E0E0",
  },
  messageButtonText: {
    color: "#1E1E1E",
    fontSize: 14,
    fontWeight: "600",
  },
  primaryActionButton: {
    flex: 1,
    height: 44,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
    backgroundColor: THEME_COLORS.primary,
    shadowColor: THEME_COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: THEME_COLORS.secondary,
  },
  primaryActionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: THEME_COLORS.background,
  },
  smallActionButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    borderWidth: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: THEME_COLORS.card,
    shadowColor: THEME_COLORS.secondary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  highlightsContainer: {
    marginVertical: 15,
  },
  highlightsContent: {
    paddingHorizontal: 5,
  },
  highlightItem: {
    alignItems: "center",
    marginHorizontal: 10,
    width: 90,
  },
  highlightImageContainer: {
    width: 80,
    height: 80,
    borderRadius: 8, // Carré avec coins arrondis
    borderWidth: 0,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 5,
    overflow: "hidden",
    backgroundColor: THEME_COLORS.card,
    shadowColor: THEME_COLORS.secondary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  highlightImage: {
    width: 80,
    height: 80,
    borderRadius: 0,
  },
  highlightText: {
    fontSize: 12,
    color: THEME_COLORS.textSecondary,
    textAlign: "center",
    fontWeight: "500",
  },
  newHighlightPlus: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: THEME_COLORS.card,
    justifyContent: "center",
    alignItems: "center",
  },
  tabsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: "#E5E5E5",
    backgroundColor: "#FFFFFF",
    paddingVertical: 10,
  },
  tabButton: {
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  activeTabButton: {
    borderBottomWidth: 2,
    borderBottomColor: "#E10600",
  },
  // Style spécial pour l'onglet performance - le plus important
  performanceTab: {
    flex: 1,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    marginHorizontal: 5,
    backgroundColor: "rgba(225, 6, 0, 0.1)", // Fond rouge subtil
    borderWidth: 2,
    borderColor: "rgba(225, 6, 0, 0.3)",
    shadowColor: THEME_COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    transform: [{ scale: 1.05 }], // Légèrement plus grand
  },
  activeTab: {
    backgroundColor: THEME_COLORS.card,
    borderLeftWidth: 3,
    borderLeftColor: THEME_COLORS.primary,
  },
  // Style spécial pour l'onglet performance actif
  activePerformanceTab: {
    backgroundColor: THEME_COLORS.primary,
    borderWidth: 2,
    borderColor: THEME_COLORS.primary,
    shadowColor: THEME_COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
    transform: [{ scale: 1.1 }], // Plus grand quand actif
  },
  postsContainer: {
    flex: 1,
    paddingBottom: 10,
    backgroundColor: THEME_COLORS.background,
  },
  postTile: {
    width: TILE_WIDTH - TILE_SPACING * 2,
    height: TILE_HEIGHT,
    margin: TILE_SPACING,
    borderRadius: 8,
    overflow: "hidden",
    shadowColor: THEME_COLORS.secondary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  postTileImage: {
    width: "100%",
    height: "100%",
  },
  multipleImagesIcon: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 4,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  // Styles pour les événements
  eventsContainer: {
    flex: 1,
    paddingHorizontal: 15,
    paddingBottom: 15,
    backgroundColor: THEME_COLORS.background,
  },
  eventCard: {
    marginBottom: 20,
    borderRadius: 10,
    backgroundColor: THEME_COLORS.card,
    overflow: "hidden",
    borderWidth: 0,
    shadowColor: THEME_COLORS.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  eventImage: {
    width: "100%",
    height: 180,
    resizeMode: "cover",
  },
  eventOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 10,
  },
  organizerBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: THEME_COLORS.tertiary,
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  organizerText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "bold",
    marginLeft: 4,
  },
  resultBadge: {
    backgroundColor: THEME_COLORS.primary,
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  resultText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "bold",
  },
  eventInfo: {
    padding: 15,
  },
  eventTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: THEME_COLORS.secondary,
    marginBottom: 10,
  },
  eventMeta: {
    marginTop: 8,
    backgroundColor: THEME_COLORS.cardLight,
    padding: 10,
    borderRadius: 6,
    borderLeftWidth: 2,
    borderLeftColor: THEME_COLORS.tertiary,
  },
  eventMetaItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  eventMetaIcon: {
    marginRight: 8,
    color: THEME_COLORS.textSecondary,
  },
  eventMetaText: {
    fontSize: 14,
    color: THEME_COLORS.textSecondary,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: THEME_COLORS.background,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: THEME_COLORS.secondary,
    marginTop: 15,
  },
  emptySubtitle: {
    fontSize: 14,
    color: THEME_COLORS.textSecondary,
    textAlign: "center",
    marginVertical: 10,
    lineHeight: 20,
  },
  shareButton: {
    backgroundColor: THEME_COLORS.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 20,
    shadowColor: THEME_COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  shareButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 14,
  },
  sectionHeader: {
    paddingHorizontal: 0,
    paddingVertical: 10,
    backgroundColor: THEME_COLORS.background,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: THEME_COLORS.border,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: THEME_COLORS.secondary,
  },
  sectionLink: {
    fontSize: 14,
    color: THEME_COLORS.tertiary,
    fontWeight: "500",
  },
  statsCard: {
    flexDirection: "row",
    backgroundColor: THEME_COLORS.card,
    borderRadius: 12,
    marginVertical: 15,
    padding: 20,
    minHeight: 100,
    shadowColor: THEME_COLORS.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 2,
    borderColor: "rgba(225, 6, 0, 0.2)",
    position: "relative",
    overflow: "visible",
  },
  statColumn: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 5,
    justifyContent: "center",
  },
  divider: {
    width: 1,
    height: "60%",
    backgroundColor: THEME_COLORS.border,
    marginHorizontal: 10,
    alignSelf: "center",
  },
  statIcon: {
    marginBottom: 8,
    color: THEME_COLORS.primary,
  },
  driverStatLabel: {
    fontSize: 12,
    color: THEME_COLORS.textSecondary,
    marginBottom: 4,
    textAlign: "center",
  },
  driverStatValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: THEME_COLORS.secondary,
    textAlign: "center",
  },
  achievementBadge: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: THEME_COLORS.quaternary,
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    flexDirection: "row",
    alignItems: "center",
  },
  achievementText: {
    color: THEME_COLORS.secondary,
    fontSize: 12,
    fontWeight: "bold",
    marginLeft: 4,
  },
  // Styles pour les filtres d'événements
  eventFiltersContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
    backgroundColor: THEME_COLORS.cardLight,
    borderRadius: 8,
    padding: 4,
  },
  eventFilterButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 2,
  },
  activeEventFilter: {
    backgroundColor: THEME_COLORS.primary,
  },
  eventFilterText: {
    fontSize: 12,
    fontWeight: "500",
    color: THEME_COLORS.textSecondary,
  },
  activeEventFilterText: {
    color: THEME_COLORS.background,
    fontWeight: "600",
  },

  // Styles pour les favoris
  favoritesContainer: {
    padding: 10,
    backgroundColor: THEME_COLORS.background,
  },
  favoriteItem: {
    backgroundColor: THEME_COLORS.background,
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: THEME_COLORS.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: THEME_COLORS.border,
    overflow: "hidden",
  },
  favoriteImageContainer: {
    position: "relative",
    height: 200,
    width: "100%",
  },
  favoriteImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  videoIcon: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  removeFavoriteButton: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: THEME_COLORS.secondary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  favoriteContent: {
    padding: 15,
  },
  favoriteHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  favoriteUserAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 10,
    backgroundColor: THEME_COLORS.card,
    justifyContent: "center",
    alignItems: "center",
  },
  favoriteUsername: {
    fontSize: 14,
    fontWeight: "600",
    color: THEME_COLORS.secondary,
  },
  favoriteTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: THEME_COLORS.secondary,
    marginBottom: 5,
  },
  favoriteDescription: {
    fontSize: 14,
    color: THEME_COLORS.textSecondary,
    lineHeight: 20,
    marginBottom: 10,
  },
  favoriteMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  favoriteDate: {
    fontSize: 12,
    color: THEME_COLORS.textSecondary,
  },
  favoriteLikesContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  favoriteLikes: {
    fontSize: 12,
    color: THEME_COLORS.primary,
    marginLeft: 4,
    fontWeight: "500",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontSize: 14,
    color: THEME_COLORS.textSecondary,
    marginTop: 8,
  },
  loadMoreButton: {
    backgroundColor: THEME_COLORS.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 15,
    alignSelf: "center",
    shadowColor: THEME_COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  loadMoreText: {
    color: THEME_COLORS.background,
    fontSize: 14,
    fontWeight: "600",
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  profileImageContainer: {
    marginRight: 16,
  },
  profileImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: "#E10600",
  },

  // Styles pour la nouvelle card des performances attractive
  performanceCard: {
    marginVertical: 20,
    marginHorizontal: 4,
    borderRadius: 24,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 12,
    backgroundColor: "#FFFFFF",
  },
  performanceGradient: {
    backgroundColor: "#FFFFFF",
    padding: 24,
    position: "relative",
    minHeight: 200,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(225, 6, 0, 0.1)",
  },
  performanceHeader: {
    alignItems: "center",
    marginBottom: 24,
    zIndex: 2,
  },
  performanceBadge: {
    backgroundColor: "#F8F9FA",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(225, 6, 0, 0.2)",
    marginBottom: 12,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
     justifyContent: "center",
  },
  performanceBadgeText: {
    color: "#E10600",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginLeft: 4,
  },
  performanceTitle: {
    alignItems: "center",
  },
  performanceTitleText: {
    color: "#1A1A1A",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 6,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  performanceSubtitle: {
    color: "#6B7280",
    fontSize: 15,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 20,
  },
  performanceLoading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
    zIndex: 2,
  },
  performanceLoadingText: {
    color: "#6B7280",
    fontSize: 16,
    marginTop: 16,
    fontWeight: "500",
  },
  performanceStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingHorizontal: 8,
    zIndex: 2,
  },
  performanceStatItem: {
    alignItems: "center",
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 8,
  },
  performanceStatIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#F8F9FA",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 2,
    borderColor: "rgba(225, 6, 0, 0.1)",
    shadowColor: "#E10600",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  performanceStatIconRaces: {
    backgroundColor: "rgba(225, 6, 0, 0.1)",
  },
  performanceStatIconWins: {
    backgroundColor: "rgba(255, 215, 0, 0.15)",
  },
  performanceStatIconPodiums: {
    backgroundColor: "rgba(192, 192, 192, 0.15)",
  },
  performanceStatValueWins: {
    color: "#FFD700",
  },
  performanceStatValuePodiums: {
    color: "#C0C0C0",
  },
  performanceStatContent: {
    alignItems: "center",
  },
  performanceStatValue: {
    color: "#1A1A1A",
    fontSize: 28,
    fontWeight: "900",
    marginBottom: 4,
    lineHeight: 32,
  },
  performanceStatLabel: {
    color: "#6B7280",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  performanceStatDivider: {
    width: 1,
    height: 40,
    backgroundColor: "rgba(225, 6, 0, 0.1)",
    marginHorizontal: 4,
  },
  performanceCTA: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#E10600",
    borderRadius: 16,
    padding: 20,
    marginTop: 8,
    shadowColor: "#E10600",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
    zIndex: 2,
  },
  performanceCTAContent: {
    flex: 1,
  },
  performanceCTAText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  performanceCTASubtext: {
    color: "rgba(255, 255, 255, 0.85)",
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 18,
  },
  performanceCTAIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  performanceDecorative: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
    overflow: "hidden",
    borderRadius: 24,
  },
  performanceCircle1: {
    position: "absolute",
    top: -40,
    right: -40,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(225, 6, 0, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(225, 6, 0, 0.05)",
  },
  performanceCircle2: {
    position: "absolute",
    bottom: -30,
    left: -30,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(225, 6, 0, 0.02)",
    borderWidth: 1,
    borderColor: "rgba(225, 6, 0, 0.04)",
  },
  performanceCircle3: {
    position: "absolute",
    top: 80,
    left: 30,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(225, 6, 0, 0.04)",
  },
  gridRow: {
    flexDirection: "row",
  },
  mainTabContent: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
});

export default styles;
